---
- name: Build nodes list
  ansible.builtin.import_playbook: proxmox-build-group.yml

- name: Proxmox servers provisioning
  hosts: my_proxmox_nodes
  become: true
  gather_facts: true
  tasks:
    - name: Proxmox node default configuration
      ansible.builtin.include_role:
        name: base_proxmox
