---
- name: Reboot Proxmox servers
  hosts: proxmox_nodes
  become: true
  gather_facts: false
  tasks:
    - name: Reboot 1 proxmox node at the time + wait up to 3 mins
      throttle: 1
      ansible.builtin.reboot:
        post_reboot_delay: 60
        reboot_timeout: 90
        test_command: /usr/bin/systemctl status pvedaemon
