---
- name: Update apt caches
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ apt_cache_time }}"

- name: Update all packages to the latest version
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- name: Install default packages
  ansible.builtin.apt:
    pkg: "{{ apt_pkgs_to_install }}"
    state: present
