---
- name: Install packages
  ansible.builtin.import_tasks: apt.yml

- name: Default file contents
  ansible.builtin.import_tasks: files.yml

- name: Install chrony/NTP
  ansible.builtin.import_tasks: chrony.yml
